import { StyleSheet, Platform } from 'react-native';
import { tokens } from './tokens';

export const styles = StyleSheet.create({
  // Auth
  authContainer: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
  },
  authTitle: { fontSize: tokens.fontHero, fontWeight: '800', color: tokens.green, marginBottom: 4 },
  authSub: { color: tokens.textSub, fontSize: tokens.fontBody, marginBottom: 32, fontWeight: '500' },
  authHint: {
    fontSize: tokens.fontSmall,
    color: tokens.textMuted,
    textAlign: 'center',
    marginTop: 16,
    lineHeight: 22,
  },
  lockRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 32 },
  lockText: { fontSize: tokens.fontSmall, color: tokens.textMuted },

  // Inputs
  input: {
    width: '100%',
    padding: 16,
    borderWidth: 2,
    borderColor: tokens.border,
    borderRadius: tokens.radiusSm,
    fontSize: tokens.fontLarge,
  },
  inputCenter: {
    width: '100%',
    padding: 16,
    borderWidth: 2,
    borderColor: tokens.border,
    borderRadius: tokens.radiusSm,
    fontSize: tokens.fontTitle,
    textAlign: 'center',
  },
  label: { fontSize: tokens.fontBody, fontWeight: '700', color: tokens.text, marginBottom: 8 },
  errText: { color: tokens.danger, fontSize: tokens.fontSub, marginTop: 8, fontWeight: '600' },
  linkBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: tokens.touchMin,
    marginTop: 12,
  },
  linkBtnText: { color: tokens.green, fontSize: tokens.fontSub, fontWeight: '600' },

  // Shared
  card: {
    backgroundColor: tokens.card,
    borderRadius: tokens.radius,
    padding: 20,
    borderWidth: 1,
    borderColor: tokens.border,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
      },
      android: { elevation: 2 },
    }),
  },
  bigBtn: {
    width: '100%',
    minHeight: tokens.touchMin + 4,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: tokens.radiusSm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  bigBtnText: { fontSize: tokens.fontLarge, fontWeight: '700' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 2,
    borderBottomColor: tokens.border,
    backgroundColor: tokens.card,
    minHeight: 56,
  },
  headerBack: {
    minWidth: tokens.touchMin,
    minHeight: tokens.touchMin,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    fontSize: tokens.fontTitle,
    fontWeight: '800',
    color: tokens.text,
    textAlign: 'center',
  },
  selectBtn: {
    flex: 1,
    minHeight: tokens.touchMin,
    borderRadius: tokens.radiusSm,
    borderWidth: 2,
    borderColor: tokens.border,
    backgroundColor: tokens.card,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 6,
  },
  selectBtnText: { fontSize: tokens.fontSub, fontWeight: '500', color: tokens.text },
  avatarCircle: {
    borderRadius: 100,
    backgroundColor: tokens.greenLight,
    borderWidth: 3,
    borderColor: tokens.green,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },

  // Bottom nav
  bottomNav: {
    flexDirection: 'row',
    borderTopWidth: 2,
    borderTopColor: tokens.border,
    backgroundColor: tokens.card,
    paddingBottom: Platform.OS === 'ios' ? 20 : 6,
  },
  bottomNavItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    minHeight: tokens.touchMin + 10,
    paddingVertical: 8,
  },
  bottomNavLabel: { fontSize: tokens.fontSub },

  // Camera/Album
  modeBtn: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: tokens.border,
  },
  filePickBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    width: '100%',
    minHeight: tokens.touchMin + 8,
    borderRadius: tokens.radiusSm,
    borderWidth: 2,
    borderColor: tokens.green,
    borderStyle: 'dashed',
    backgroundColor: tokens.greenLight,
    marginBottom: 16,
  },
  albumItem: {
    borderRadius: tokens.radiusSm,
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  albumCheck: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: tokens.green,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Feedback
  fbBtn: {
    flex: 1,
    minHeight: tokens.touchMin,
    borderRadius: tokens.radiusSm,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: tokens.border,
    backgroundColor: tokens.card,
  },
  fbBtnText: { fontSize: tokens.fontBody, fontWeight: '700', color: tokens.textSub },

  // Record
  periodBtn: {
    flex: 1,
    minHeight: 42,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: tokens.border,
  },

  // Settings
  sectionLabel: {
    fontSize: tokens.fontSub,
    color: tokens.textMuted,
    fontWeight: '700',
    marginLeft: 16,
    marginTop: 20,
    marginBottom: 8,
  },
  menuGroup: {
    marginHorizontal: 16,
    borderRadius: tokens.radiusSm,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: tokens.border,
  },

  // Lifestyle
  sectionTitle: {
    fontSize: tokens.fontBody,
    fontWeight: '800',
    color: tokens.text,
    marginTop: 20,
    marginBottom: 10,
  },
  optionBtn: {
    minHeight: tokens.touchMin + 12,
    borderRadius: tokens.radiusSm,
    borderWidth: 2,
    borderColor: tokens.border,
    backgroundColor: tokens.card,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    padding: 10,
  },
  exerciseBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    minHeight: tokens.touchMin + 8,
    borderRadius: tokens.radiusSm,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 2,
    borderColor: tokens.border,
    backgroundColor: tokens.card,
    marginBottom: 8,
  },
});
